### ISSUE TITLE
wikimedia commons supported video format

### ISSUE THREAD

**Issue by ghost** [you-apps/RecordYou#177]
### Describe your suggested feature

* app works flawlessly and its on fdroid
* can you please add support for any one of the following format_ .webm, .ogg or mp1 & mp2 as given @ https://commons.m.wikimedia.org/wiki/Commons:Video#UPLOAD

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SilverPuppy** [comment]
Those are older formats, but adding Theora support should be really easy, I'd imagine, as it was FOSS from the beginning. MPEG1 and MPEG2 were patent-encumbered at one time, but they have apparently lapsed. MPEG2 is well supported with FOSS libraries as well. None of the formats they support give the quality at a given bitrate that h264 and h265 offer, but I understand why they wish to avoid them, and agree it's probably a good idea.

**Comment by SilverPuppy** [comment]
Which webm CODECs does the webm support just added offer? They're quite specific about which ones are acceptable.

**Comment by SuhasDissa** [comment]
VP8 and VP9

**Comment by SilverPuppy** [comment]
> VP8 and VP9

That definitely will resolve the issue, and probably those are the best options from the available ones. Thank you very much for the time and effort you invested in this.

**Comment by SuhasDissa** [comment]
Please not that VP9 codec was added in Android 13. So you'll need a newer device to use VP9. VP8 will work on all devices.

**Comment by SuhasDissa** [comment]
Also, for some reason the audio codec is hardcoded as AAC in the screen recoder. So it will use AAC codec with the chosen video codec.

https://github.com/you-apps/RecordYou/blob/main/app%2Fsrc%2Fmain%2Fjava%2Fcom%2Fbnyro%2Frecorder%2Fservices%2FScreenRecorderService.kt#L103

**Comment by SilverPuppy** [comment]
> Also, for some reason the audio codec is hardcoded as AAC in the screen recoder. So it will use AAC codec with the chosen video codec.
> 
> https://github.com/you-apps/RecordYou/blob/main/app%2Fsrc%2Fmain%2Fjava%2Fcom%2Fbnyro%2Frecorder%2Fservices%2FScreenRecorderService.kt#L103

Ouch. That's a huge problem. AAC is patent-encumbered, and not eligible for upload at WikiMedia. It should be using Vorbis or Opus to be eligible. AAC isn't even correct for the WebM standard, which also calls for Vorbis or Opus, although it will usually work, as the Matroska container used for WebM supports AAC, and most players can decode it.

Unfortunately, the work you did resolves the specific feature requested, but reveals a second change needed to fully resolve the OP's request, I.e., to be able to directly record WikiMedia compliant video files.

**Comment by SuhasDissa** [comment]
@Bnyro is there a reason for hardcoding the AAC codec for screen recordings?
