### ISSUE TITLE
App shouldn't launch when recording with Quick Settings

### ISSUE THREAD

**Issue by decipher3114** [you-apps/RecordYou#186]
### Steps to reproduce

1. Click Record option from Quick Settings.
2. The app is launched

### Expected behavior

The app shouldn't launch and only the corresponding recording should start.

### Actual behavior

The app opens.

### Record You version

All released versions

### Android version

Probably all

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by MikeStirner** [comment]
When I follow your steps to reproduce it on my Samsung S20, it does take me to the app with a box in the bottom that is kind of asking my permission to start recording. And I just hit start recording, but then, I get the notification saying that it's recording and the timer is counting, but on the screen it still shows the record button ready to be pressed. And I've seen this before and what's happening is that it acts like it's recording kind of, but it's not really recording anything. And then I press record again, actually starts recording and shows it in the app's UI and everything. And this is a problem that happened all the time before I stopped optimizing the battery.
