### ISSUE TITLE
scrool view

### ISSUE THREAD

**Issue by gimas146** [you-apps/RecordYou#187]
### Describe your suggested feature

add srcoll view in settings menu

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Settings are scrollable in debug builds.

**Comment by SuhasDissa** [comment]
@gimas146 does this make the last setting options unusable for you?
