### ISSUE TITLE
the possibility of going back to the previous design, I'm sure the new one is worse....

### ISSUE THREAD

**Issue by Wjxfi** [you-apps/RecordYou#188]
the possibility of going back to the previous design, I'm sure the new one is worse....

**Comment by SuhasDissa** [comment]
The new design uses more Material You colors than the previous design. This can make the design look more vibrant and modern, but it can also make it look overwhelming if you choose too many saturated colors.

To get the best results, try using less saturated colors and a limited color palette. We're also using a bottom bar for navigation, which makes the design more self-explanatory and easier to use for new users.

I hope this is helpful!
