### ISSUE TITLE
Skip Silence

### ISSUE THREAD

**Issue by shuvashish76** [you-apps/RecordYou#189]
### Describe your suggested feature

Feature request for skip silence while recording.
Use case: Recoding some audio lecture, debates, news etc..

### Other details

[Audio Recorder](https://www.f-droid.org/packages/com.github.axet.audiorecorder/) has this feature. Also check if it's possible for video recorded.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by RokeJulianLockhart** [comment]
@SuhasDissa, why https://github.com/you-apps/RecordYou/issues/189#event-11922912313?

**Comment by shuvashish76** [comment]
> We haven't had a chance to tackle this yet due to other priorities, so we're going to mark this feature as "not planned" for now.

Understandable but IMO would have been better to mark it as "Low Priority" or "Priority 5" than closing the issue for other interested devs to look into it.
