### ISSUE TITLE
no amplification/ normalisation

### ISSUE THREAD

**Issue by firefoxlover** [you-apps/RecordYou#192]
### Steps to reproduce

I am sorry to say that, but for recording anything but direct voice input the app is not suited at all.

I tried recording guitar from like 30cm distance. The volume peaks where really tiny, and so was the recording.

It also went silent again really quickly, in total very bad.

Compared to [AudioRecorder](https://github.com/Dimowner/AudioRecorder) which worked perfectly fine.

If your intention is support for anything but direct voice input this should be fixed. If not, please mention the restriction in the Apps description on F-Droid.

### Expected behavior

When recording something a little bit more silent, it should auto amplify the sound. Also no effects on bringing down the volume please.

### Actual behavior

The app seems to be extremely tuned for spoken voice. P, k, s, f sounds, direct input, veeery low treble.

Please mention this.

### Record You version

7.0

### Android version

Grapheneos Android 13

### Other details

Tested with internal and lav mic.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Feel free to either enable the "lossless recorder (wav)" option in Record You or to uninstall the app and use a different one.

**Comment by SuhasDissa** [comment]
Switching the audio source in the app settings might fix some audio quality related problems.
Audio sources like Camcorder is for stereo recording. It may not be the best option for voice recording.

![image](https://github.com/you-apps/RecordYou/assets/64766434/fd12bbc2-1d64-4cd5-8aa7-31b0b0c72563)

**Comment by firefoxlover** [comment]
Hey, sorry for the harsh comment.

Really strange, I gave it another try. No preset, even "unmodified" could recreate this, I tried WAV and opus, no problems.

Strange a guitar recording hat different pitch! But I will report this elsewhere.

Really good sound quality, no idea what the course was.
