### ISSUE TITLE
Can't trim video

### ISSUE THREAD

**Issue by daudtivan** [you-apps/RecordYou#197]
### Steps to reproduce

Using the app in android 9 with classic nav bar
The "Trim" button is positioned behind the home button and can't be accessed.

### Expected behavior

Should be able to click the trim button

### Actual behavior

Button is behind home button

### Record You version

7.0

### Android version

9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please share a screenshot or screen recording of the issue.
