### ISSUE TITLE
Asks for recording when switching tab only

### ISSUE THREAD

**Issue by kik-btaski** [you-apps/RecordYou#207]
### Steps to reproduce

1. Add record screen option to your notification bar.

https://github.com/you-apps/RecordYou/assets/142499381/446236dc-1581-492d-a65b-8b34023205bd

2. Click on same record screen button. It will open the app(probably in `Record sound` tab) and ask for record **screen**. Tap start now.
3. Now stop the recording. After stoping it, you will find yourself in `Record Sound` tab
4. Switch to `Record screen` tab. It will again ask for recording.

### Expected behavior

It shouldn't ask for recording when only switching tab

### Actual behavior

It ask for recording again.

### Record You version

7.1

### Android version

Android 11

### Other details

Samsung oneUI version: 3.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Fixed in https://github.com/you-apps/RecordYou/commit/554dea680a11fbb75635eb8b823783f825efbed8#diff-3ad4623e6cfedd69153799fd6ce5f6988b1797d7de65422c018b4746d9b7ec31R29.
