### ISSUE TITLE
Quick restart button

### ISSUE THREAD

**Issue by Cwpute** [you-apps/RecordYou#211]
### Describe your suggested feature

I use RecordYou to record myself playing my instrument and need to restart my recording several times un a row sometimes.

I'd love to have a dedicated button directly on the Recording screen to restart it, wuthout having to stop it, delete it from the notification, and start it again.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We don't need that in my opinion, the two necessary button preses only cost you about a second which is fine.

**Comment by Cwpute** [comment]
It is fine, yes, but this additional button would still help save a lot of manipulation and waiting for the app to get into a state of recwrding again. It is also costly for me, because i need to stay focused on my music while i navigate the app.
Sure it.s only two button presses, but it's two button presses that make a difference
