### ISSUE TITLE
Ask record name after recording

### ISSUE THREAD

**Issue by Cwpute** [you-apps/RecordYou#212]
### Describe your suggested feature

While i appreciate the default naming options in the settings, i'd prefer the app to ask me for the name of the record everytime i end one.

Add an option to ask for the record name after it ended.

### Other details

You may as well add an option to ask for it before it is recorded.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That'd be kinda hard to implement since it's possible to stop the recording via the notification.

You can easily rename the recording in the library tab once it's finished which is sufficient imo.
