### ISSUE TITLE
Continuos Audio Record

### ISSUE THREAD

**Issue by GuiSousa135** [you-apps/RecordYou#216]
### Describe your suggested feature

I use and like Record You very much, but I would like to see the continuous recording function of audio in backgroud (like a security camera with dvr that keeps recent recordings and excludes old recordings). It would enable the user to record 24 hours continuously, without the file corrupting or occupying much memory, since it would be recorded in parts (such as 30 minuntos, 1 hour recording).

### Other details

A very cool project for android that has this function is the Alibi recorder (https://github.com/Myzel394/Alibi).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's out of scope for the project.
