### ISSUE TITLE
RecordYou stops recording at a file size of about 4.5gb

### ISSUE THREAD

**Issue by 3mmanuelCH** [you-apps/RecordYou#217]
### Steps to reproduce

• Begin Recording.
• Launch desired application.
• After recording, I return to RecordYou to stop the recording, or I do it from my notifications panel.
• I save and then I playback the recorded clip.
• Dissapointment.

### Expected behavior

It should record the full clip
Side note: I do prefer the cleaner look of the older versions of RecordYou. The current UI seems a bit too amateurish.

### Actual behavior

After the record has been initiated, I open any game and begin recording at 2KUHD 70mbps variable Frame rate, (which is well within my device's capability to record) but after just about 4 minutes of recording or 4.5gb, the app crashes regardless of how many times I rerun this process. I have provided much more than enough storage space, excluded the app from every form of Battery Optimization, and I've given it whatsoever permission it requires, but still no sign of improvement. Please fix.

### Record You version

7.1

### Android version

Android 9

### Other details

I truly appreciate what the team at RecordYou have designed for the common man. It's an app that will never get deleted from my smartphone, but where it fails to impress, it fails gravely. So sorry if I sound harshly.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SuhasDissa** [comment]
This is not a problem with the app. Android 9 doesn't support video files larger than 4GB.

**Comment by 3mmanuelCH** [comment]
> This is not a problem with the app. Android 9 doesn't support video files larger than 4GB.

**Comment by 3mmanuelCH** [comment]
Thanks for the clarification. That being the case, I'd still appreciate if there were ways to go around this. 

As a suggestion, I'd love if RecordYou could implement a feature where a user can perform seamless batch recordings. For instance:
I could give the recorder constrained parameters at which file size to end my recording... and to automatically begin a fresh recording from that point, then Rinse and repeat till I choose to end the sequence.

A very popular use case for this would be:
Content creators trying to capture unexpected hype footage from their daily gameplay without having to painstakingly comb through a single ginormous 100GB footage
