### ISSUE TITLE
Default storage location

### ISSUE THREAD

**Issue by aclifton314** [you-apps/RecordYou#222]
### Steps to reproduce

1) Record audio
2) Select Choose Directory in settings

### Expected behavior

No specific expected behavior.

### Actual behavior

Taken to Pixel 7a base directory.

### Record You version

7.1

### Android version

14

### Other details

I have a Pixel 7a and was just curious what the default storage location was for recorded audio. When I select "Choose Directory" from the settings, I am taken to the base Pixel 7a directory. I can see the audio I recorded in the app, but when I switched the directory to save new audio files, I can't seem to locate the previous files I had recorded.

Let me know if you need any other information. Thanks in advance!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It's inside the local storage of the app by default.

**Comment by aclifton314** [comment]
How does one access the local storage of the app?
