### ISSUE TITLE
Option to disable notification or make it a toast, view recorded files at main menu.

### ISSUE THREAD

**Issue by PRinceBhai** [you-apps/RecordYou#223]
### Describe your suggested feature

1. Instead of having a notification appear when a recording is finshed/stopped make it appear as a toast or outright disable this feature.

2. Option to view files directly on the main/home screen of the app where we also have the option to press record.

Not urgent :
3. Add a basic spectrogram view of the audio recording right next to the file name in a list (like we have in apps like WhatsApp, telegram).

Thankbyou for this great app! :D

### Other details

Only two requests, you can ignore the third one if it isn't worth it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SuhasDissa** [comment]
1. You can go-to notification settings of this app and disable the "recording finished" notification

**Comment by PRinceBhai** [comment]
@SuhasDissa That's what I did, but if possible plewse make it an option to switch it to a toast instead or an option to disable in the app. Thanks.

**Comment by Bnyro** [comment]
2. That's not planned, it'd look awful and messy.
3. I don't think that's possible or useful.
