### ISSUE TITLE
Movable Screen Record Annotation

### ISSUE THREAD

**Issue by Eliya-Manoj** [you-apps/RecordYou#227]
### Describe your suggested feature

Like this

https://github.com/you-apps/RecordYou/assets/90308888/f72f6912-a698-4832-b6ea-428705911198

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by user8446** [comment]
Hi, not only is it not movable, but it cannot be dismissed by clicking "X", which would be a bug: 

![Screenshot_20231217-104947](https://github.com/you-apps/RecordYou/assets/18019245/a7b39b00-4015-4994-921f-507e4272fce5)

**Comment by SuhasDissa** [comment]
"X" button is to close the canvas. It doesn't close the toolbar

**Comment by user8446** [comment]
Thank you. That whole overlay is not dismissable and not movable. It happens to be right where I need to interact with an app to record.
