### ISSUE TITLE
Add more annotation tools +  one-tap delete of all annotations

### ISSUE THREAD

**Issue by ElsAr4e** [you-apps/RecordYou#228]
### Describe your suggested feature

Please add more annotation tools:

Examples
https://github.com/egorolegovichyakovlev/DroidRec/issues/2

And add a button that allows you to delete all annotations with one tap.

The support of keyboard shortcuts if you are using a bluetooth / USB- keyboard would be great.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
> And add a button that allows you to delete all annotations with one tap.
>
There already is such a button.

> The support of keyboard shortcuts if you are using a bluetooth / USB- keyboard would be great.
> 
That's out of scope, it's an Android app, not a desktop app.
