### ISSUE TITLE
In-app video compression option

### ISSUE THREAD

**Issue by KraXen72** [you-apps/RecordYou#231]
### Describe your suggested feature

some messaging apps don't support video above x mb, and it's cumbersome to export video to file due to SAF, so same as trim option, please add compression with a MB target, which calculates the minimum needed compression to meet that mb targert, and then compresses it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SuhasDissa** [comment]
Integrating video processing libraries will significantly increase the size of the app. Additionally, we would need to create separate APKs for different CPU architectures, which exceeds the scope of this project.
I recommend you to find a dedicated app for video compression.

**Comment by KraXen72** [comment]
however, there aren't many video compression apps which support importing a file from a share dialog. could you atleast add a 'save file to storage' option for the videos, since they're in SAF and can't be exported easily? thanks!

**Comment by shuvashish76** [comment]
We've [FFShare](https://github.com/caydey/ffshare) app for this which uses ffmpeg.
I agree that increasing app size heavily for this purpose isn't worth for it.

**Comment by KraXen72** [comment]
good to know, thanks
