### ISSUE TITLE
Recordings shouldn't be saved in /Android/data

### ISSUE THREAD

**Issue by mario-g98** [you-apps/RecordYou#241]
It took me some time to find where the recordings went. I saw the option in settings to change the directory, but the default behaviour should be save the files in a directory outside /Android,  as in the recent Android versions it is almost impossible to access the files inside. Another point is that I expected the recording to show up in my gallery, but this didn't happen because they were in /Android

I have 2 suggestions:

- save the files in /RecordYou
- save voice recordings in /Recordings and screen recordings in /Pictures/Screenshots, as this is the default android behaviour. 

Edit: I was going to open another issue, but I will add it here:

Give an option to choose separate locations for audio and video, as mixing them in one directory is not ideal.

**Comment by libreom** [comment]
True, videos should appear in gallery and file manager👍

**Comment by Bnyro** [comment]
Being able to save files in the internal app data is considered a privacy feature as other apps can't access your private recordings. Recordings can be exported from there, so that's not an issue.

Apart from that you can still manually change the recordings folder.

Concerning having different locations for storing screen and voice recordings - I personally do think that it's sufficient to have one directory for both, but please open a different discussion for that, as it's not related to the issue here.

**Comment by libreom** [comment]
@Bnyro please add export or share to storage/file option, I don't have any such option other than upload to drive

**Comment by mario-g98** [comment]
Correct me if I am wrong, but a voice / screen recorder is a tool and not a privacy oriented app. It is not different than a camera app. Therefore the files generated by it should be easily accessible to other apps.

**Comment by Bnyro** [comment]
> Correct me if I am wrong, but a voice / screen recorder is a tool and not a privacy oriented app. It is not different than a camera app. Therefore the files generated by it should be easily accessible to other apps.
>
All "You Apps" are privacy oriented, so it doesn't matter what other recorder apps do.

**Comment by mario-g98** [comment]
> > Correct me if I am wrong, but a voice / screen recorder is a tool and not a privacy oriented app. It is not different than a camera app. Therefore the files generated by it should be easily accessible to other apps.
> 
> All "You Apps" are privacy oriented, so it doesn't matter what other recorder apps do.

Ok then, I guess I have missed the part that there are many "You Apps" that are privacy oriented :)

**Comment by libreom** [comment]
Where is the export option?
