### ISSUE TITLE
RY doesn't show the green mic notification when a recording is running

### ISSUE THREAD

**Issue by serrq** [you-apps/RecordYou#252]
### Steps to reproduce

Just perform an audio registration

### Expected behavior

The green mic symbol should be shown

### Actual behavior

It doesn't shown

### Record You version

7.2 fdroid

### Android version

Android 13

### Other details

![1000105809](https://github.com/you-apps/RecordYou/assets/113377431/e4e76597-3786-430e-9dc1-529c74b868d3)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
If so, that's an Android issue. Android has to detect when the mic is used, that's not our task.
