### ISSUE TITLE
Strange behavior: green mic notification starts when app is in foreground

### ISSUE THREAD

**Issue by serrq** [you-apps/RecordYou#253]
### Steps to reproduce

After reinstallation, the green mic notification seems run, but not properly.

In others similar apps the green mic notification is ON only when a recording is running.

In RY it is always on in foreground, even if no one recording is in esecution.

### Expected behavior

Just starts-stop when a recording is running

### Actual behavior

Always active.

### Record You version

7.2

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

![1000105815](https://github.com/you-apps/RecordYou/assets/113377431/d8c52e7a-fcda-4920-96da-917e76fdc12b)

**Comment by Bnyro** [comment]
Closing as not reproducible and if it happens, it's an Android issue if the OS can't detect that the microphone it is controlling is being used...
