### ISSUE TITLE
Bad permission (in my opinion)

### ISSUE THREAD

**Issue by serrq** [you-apps/RecordYou#254]
### Steps to reproduce

It is built in the code, natively.

### Expected behavior

The app can rise the volume of the speaker by itself without any human action. It can compromise my privacy if accidentally happen during a meeting unauthorized recording.

### Actual behavior

Read above

### Record You version

7.2

### Android version

Android 13

### Other details

![1000105813](https://github.com/you-apps/RecordYou/assets/113377431/c4a35daf-d7f8-4f6d-9614-3b19b9228e63)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That setting is needed for bluetooth headphones compatibility for void recording.
