### ISSUE TITLE
App doesn't stop recordings when device is powered off resulting in corrupted files

### ISSUE THREAD

**Issue by MikeStirner** [you-apps/RecordYou#258]
### Steps to reproduce

Start a screen recording and then turn off your device.

### Expected behavior

It should end the recording so it saves properly.

### Actual behavior

It corrupts the mp4 video file and won't play.

### Record You version

7.3

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by jorfus** [comment]
Seems possibly related to an issue I had today where I saw a notification about an ongoing recording several hours into it, and the green recording icon hadn't been showing.

The app showed no recording going on, so I stopped it via the notification which resulted in a corrupted file and severe slowdown of my phone for about a minute, but the file was quite large, of course.

I had only locked the screen during those hours, not turned the phone off.

I've so far failed to reproduce it with shorter recordings.
