### ISSUE TITLE
Allow pausing the recording from the quick settings tiles

### ISSUE THREAD

**Issue by pvagner** [you-apps/RecordYou#263]
### Describe your suggested feature

Currently quick settings tiles Record sound and Record screen start the recording in the same way pressing the Record action button on the app main screen would do.
However when the recording is already in progress, pressing quick tile again starts the new recording I think pressing the tile while the recording is in progress should stop the recording to provide better user experience.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not necessary, you can use the notification for that.

**Comment by pvagner** [comment]
Hello,
I see your point that this functionality is available through the notification. However then I am thinking this might be a bug as clicking the quick tile when the recording is already started leads to an unexpected state.
I think reconsidering this may help everyone.

**Comment by Bnyro** [comment]
There's enough stuff to work on, and this is probably not an important one.

You can open a pull request if you want to, but otherwise this is not going to be worked on.
