### ISSUE TITLE
Screen record not working

### ISSUE THREAD

**Issue by heberjeur** [you-apps/RecordYou#264]
### Steps to reproduce

1-    Click on the screen record menu.
2-   Press the red circle button to start recording.

### Expected behavior

The screen recording should start without any issues.

### Actual behavior

A black blur overlay appears instead of initiating the recording.

https://github.com/you-apps/RecordYou/assets/11852634/40f19018-5cc9-41b6-8891-cdf93799fa9e

### Record You version

7.3

### Android version

Android 11

### Other details

- It seems there might be a problem with the accessibility service that needs to be addressed.
- This issue persists across all previous versions of the application.
- My phone is Samsung A50

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SuhasDissa** [comment]
Do you have the screen annotation tool enabled?

**Comment by SuhasDissa** [comment]
Are you trying to run two screen recording apps simultaneously?

**Comment by heberjeur** [comment]
I tried both with and without annotations enabled and disabled.
Normally, I only use your application, "Record You."
Just this time, to demonstrate the issue and to send you a screen recording of what I can see, I used two applications simultaneously.

**Comment by SuhasDissa** [comment]
Cannot reproduce in Andriod 11 (Samsung)

**Comment by heberjeur** [comment]
Can you send to me a debug apk ?

**Comment by SuhasDissa** [comment]
You can grab one from here : https://github.com/you-apps/RecordYou/actions
