### ISSUE TITLE
Bug: Screen annotation setting detected incorrectly after app install

### ISSUE THREAD

**Issue by JonnyTech** [you-apps/RecordYou#279]
### Steps to reproduce

Press record button
Draw over other apps message shown
Unable to continue

### Expected behavior

Ability to record screen

### Actual behavior

See screenshot below

### Record You version

7.3 from fdroid

### Android version

Android 13

### Other details

![nwo5hkr5lc9n3rjx](https://github.com/you-apps/RecordYou/assets/3584732/6ec3035a-be8d-4c74-b51f-7c139c06c00c)

Device is an Android Go so that feature is not available

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Unfortunately, Android Go disables the "Display over other apps" feature, so the screen annotation cannot be supported on such devices.

**Comment by Bnyro** [comment]
Did you disable the screen annotation tool in the settings?

**Comment by JonnyTech** [comment]
I simply installed the app and tapped the screen record button, no changes to any settings.

The screen recording annotation is disabled by default. Enabling it makes no difference.

But after I enable it and then disable it, then the screen recording works correctly.

Therefore there is a logic bug in the application first run. Thank you for your support.
