### ISSUE TITLE
add support for internal audio (ROOT)

### ISSUE THREAD

**Issue by rajarshikhatua100** [you-apps/RecordYou#281]
### Describe your suggested feature

in screen recorder there is no internal audio support, it could be done without root in older Android versions but latest Android versions need root or maybe some form of magisk/kernelsu module.

### Other details

I have seen this [app](https://gitlab.com/vijai/screenrecorder) do it with its [magisk module](https://gitlab.com/vijai/screencam-magisk-module) but in my phone (Samsung Galaxy M31) it doesn't work 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ego-lay-atman-bay** [comment]
When you say internal audio, do you mean audio that is playing on the phone? If so, I don't think it requires root, because I've seen other screen recorder apps that are able to record the device audio (not mic) without issues.

**Comment by SuhasDissa** [comment]
A lot of apps use [`AudioPlaybackCapture`](https://developer.android.com/reference/android/media/AudioPlaybackCaptureConfiguration). It has some limitations compared to just using root permissions.
Also implementing this would require a complete rewrite of the screen recorder code.
