### ISSUE TITLE
Widget with Material You

### ISSUE THREAD

**Issue by GuiSousa135** [you-apps/RecordYou#282]
### Describe your suggested feature

A widget to start audio recording quickly and directly from the home screen through a standard widget with the Material You theme (like a 1x2 button)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You can use the already existing app shortcuts for that.
