### ISSUE TITLE
录音格式支持MP3

### ISSUE THREAD

**Issue by JSCSZZSS** [you-apps/RecordYou#285]
### Describe your suggested feature

希望录音格式支持MP3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SuhasDissa** [comment]
目前 Android 框架中没有内置 MP3 编码器。 请使用音频转换工具将M4A转换为MP3。
