### ISSUE TITLE
Convert record you to system app using shizuku

### ISSUE THREAD

**Issue by Gamer750** [you-apps/RecordYou#286]
### Describe your suggested feature

Convert record you to system app using shizuku

### Other details

If it shizuku it would be less riskier than rooting

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SuhasDissa** [comment]
I don't think shizuku can do this.
Shizuku can only do shell level stuff. It doesn't have any root or system permissions. Enabling Internal audio recording cannot be done using the shell.
