### ISSUE TITLE
Push-To-Talk to start recording

### ISSUE THREAD

**Issue by MageSlayer** [you-apps/RecordYou#287]
### Describe your suggested feature

Hi
I have an Android phone with "Push-To-Talk" separate button at its side.
It would be super convenient to just press that button to start audio recording without unlocking phone first, going to menu to find application & pressing buttons when it starts.

Personally, I find this feature so lacking when driving, running, meditating, etc.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Due to tue fact that we don't have phones with such a button and such buttons are not common / very rare, that's out of scope.
