### ISSUE TITLE
 System sound recording can be added to the recording screen, and system sound recording and microphone recording can be simultaneously performed

### ISSUE THREAD

**Issue by JSCSZZSS** [you-apps/RecordYou#291]
### Describe your suggested feature

I hope that in addition to the absence of sound and microphone sound, the recording screen can be added to system sound recording, and also system sound recording and microphone recording at the same time

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/you-apps/RecordYou/discussions/232
